[info] Running ijeuler.P008 
[debug] Starting sandboxed run...
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	C:\Users\Rhys\Documents\Java\IdeaProjects\ScalaModules2\target\scala-2.8.1.final\classes
[debug] 	C:\Users\Rhys\Documents\Java\IdeaProjects\ScalaModules2\project\boot\scala-2.8.1\lib\scala-library.jar
[debug] Waiting for thread run-main to exit
java.lang.ClassNotFoundException: ijeuler.P008
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at sbt.Run.getMainMethod(Run.scala:65)
	at sbt.Run.run0(Run.scala:52)
	at sbt.Run.execute$1(Run.scala:42)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:46)
	at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
	at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
[debug] 	Thread run-main exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.Predef$.error(Predef.scala:58)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1005)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1005)
	at scala.Option.foreach(Option.scala:185)
	at sbt.BuildCommon$class.toError(Defaults.scala:1005)
	at sbt.Defaults$.toError(Defaults.scala:30)
	at sbt.Defaults$$anonfun$runMainTask$2$$anonfun$apply$18.apply(Defaults.scala:375)
	at sbt.Defaults$$anonfun$runMainTask$2$$anonfun$apply$18.apply(Defaults.scala:374)
	at sbt.Scoped$$anonfun$hf4$1.apply(Structure.scala:508)
	at sbt.Scoped$$anonfun$hf4$1.apply(Structure.scala:508)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:304)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:304)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[error] {file:/C:/Users/Rhys/Documents/Java/IdeaProjects/ScalaModules2/}default-f0cdb9/run-main: Nonzero exit code: 1
